steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/pss-bot-437619/pssbot/bot', '.' ]
images:
- 'us-central1-docker.pkg.dev/pss-bot-437619/pssbot/bot'

options:
  logging: CLOUD_LOGGING_ONLY